name: gcc

on:
  push:
    branches: [ master, chaos ]
  pull_request:
    branches: [ master, chaos ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libraries
        run: sudo apt-get update && sudo apt-get -y install libdbus-1-dev libcapstone-dev libtbb-dev libdebuginfod-dev libxkbcommon-dev libegl-dev libwayland-dev
      - name: Profiler GUI
        run: make -j`nproc` -C profiler/build/unix debug release
      - name: Update utility
        run: make -j`nproc` -C update/build/unix debug release
      - name: Capture utility
        run: make -j`nproc` -C capture/build/unix debug release
      - name: Csvexport utility
        run: make -j`nproc` -C csvexport/build/unix debug release
      - name: Import-chrome utility
        run: make -j`nproc` -C import-chrome/build/unix debug release
      - uses: actions/upload-artifact@v3
        with:
          name: binaries-linux
          path: |
            profiler/build/unix/Tracy-release
            update/build/unix/update-release
            capture/build/unix/capture-release
            csvexport/build/unix/csvexport-release
            import-chrome/build/unix/import-chrome-release
  build-macos:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Install libraries
      run: brew install capstone tbb pkg-config glfw
    - name: Profiler GUI
      run: make -j`nproc` -C profiler/build/unix debug release
    - name: Update utility
      run: make -j`nproc` -C update/build/unix debug release
    - name: Capture utility
      run: make -j`nproc` -C capture/build/unix debug release
    - name: Csvexport utility
      run: make -j`nproc` -C csvexport/build/unix debug release
    - name: Import-chrome utility
      run: make -j`nproc` -C import-chrome/build/unix debug release
    - uses: actions/upload-artifact@v3
      with:
        name: binaries-macos
        path: |
          profiler/build/unix/Tracy-release
          update/build/unix/update-release
          capture/build/unix/capture-release
          csvexport/build/unix/csvexport-release
          import-chrome/build/unix/import-chrome-release
